services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "127.0.0.1:4317:4317"  # OTLP gRPC
      - "127.0.0.1:4318:4318"  # OTLP HTTP
    depends_on:
      - loki

    networks:
      - observability

  loki:
    image: grafana/loki:3.5.8
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    depends_on:
      - loki
    networks:
      - observability

networks:
  observability:

volumes:
  loki-data:
  tempo-data:
  prometheus-data:
  grafana-data:
