services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    env_file: .env
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:           # <-- attach it here
      - proxy-network
      
volumes:
  portainer_data:

networks:
  proxy-network:
    external: true