services:
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    restart: always
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:           # <-- attach it here
      - proxy-network

volumes:
  pgadmin_data:

networks:
  proxy-network:
    external: true