services:
  auth:
    build: ./auth
    command: pnpm dev
    env_file:
      - .env
    networks:
      - proxy-network
    environment:
      AUTH_PORT: ${AUTH_PORT}
    ports:
      - "127.0.0.1:${AUTH_PORT}:${AUTH_PORT}"
    volumes:
      - ./auth:/app
      - /app/node_modules

networks:
  proxy-network:
    external: true