services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${BACKEND_API_PORT}:${BACKEND_API_PORT}"
    env_file: 
      .env
    environment:
      BACKEND_DATABASE_URL: ${BACKEND_DATABASE_URL}
      BACKEND_OPEN_API_KEY: ${BACKEND_OPEN_API_KEY}
      BACKEND_LOG_LEVEL: info
      BACKEND_API_PORT: ${BACKEND_API_PORT}
      BACKEND_WRITE_TO_DB: "true"
      BACKEND_CLEAR_LOGS_ON_START: "false"
      BACKEND_PROCESS_WITH_AI: "true"
      BACKEND_AI_MAX_ATTEMPTS: ${BACKEND_AI_MAX_ATTEMPTS}
      BACKEND_POPULATE_INITIAL_DATABASE: "true"
      BACKEND_CORS_ALLOWED_URL: ${BACKEND_CORS_ALLOWED_URL},
      BACKEND_DEBUG_REQUESTS: false,
      BACKEND_DEBUG_RESULTS: false,
      BACKEND_RATE_LIMIT_MAX_REQUESTS: ${BACKEND_RATE_LIMIT_MAX_REQUESTS},
      BACKEND_RATE_LIMIT_WINDOW_MS: ${BACKEND_RATE_LIMIT_WINDOW_MS}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://alloy:4318}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-production}
    volumes:
      - logs:/app/logs
    networks :
      - proxy-network
      - monitoring-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_FRONTEND_API_URL: ${VITE_FRONTEND_API_URL}
    ports:
      - "127.0.0.1:${FRONTEND_API_PORT}:80"
    env_file: 
      .env
    environment:
      VITE_FRONTEND_API_URL: "${VITE_FRONTEND_API_URL}"
    depends_on:
      - backend
    networks:           
      - proxy-network

volumes:
  logs:

networks:
  proxy-network:
    external: true
  monitoring-network:
    external: true

