version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_DB: authentik
    secrets:
      - postgres_password
      - postgres_user
    networks:
      - authentik-internal

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - authentik-internal

  server:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_SECRET_KEY_FILE: /run/secrets/authentik_secret_key
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER_FILE: /run/secrets/postgres_user
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD_FILE: /run/secrets/postgres_password
      AUTHENTIK_REDIS__HOST: redis
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    secrets:
      - postgres_password
      - postgres_user
      - authentik_secret_key
    networks:
      - authentik-internal
      - proxy-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authentik.rule=Host(`auth.abrahamgreenberg.co.uk`)"
        - "traefik.http.routers.authentik.entrypoints=websecure"
        - "traefik.http.routers.authentik.tls=true"
        - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
        - "traefik.http.services.authentik.loadbalancer.server.port=9000"
        # Forward Auth
        - "traefik.http.middlewares.authentik.forwardauth.address=http://tasks.server:9000/outpost.goauthentik.io/auth/traefik"
        - "traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"


  worker:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_SECRET_KEY_FILE: /run/secrets/authentik_secret_key
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__USER_FILE: /run/secrets/postgres_user
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD_FILE: /run/secrets/postgres_password
      AUTHENTIK_REDIS__HOST: redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik_media:/media
      - authentik_templates:/templates
    secrets:
      - postgres_password
      - postgres_user
      - authentik_secret_key
    networks:
      - authentik-internal

volumes:
  authentik_db:
  authentik_media:
  authentik_templates:

networks:
  authentik-internal:
    driver: overlay
    attachable: true
  proxy-network:
    external: true

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  authentik_secret_key:
    external: true
