services:
  # MariaDB database for Nginx Proxy Manager
  npm-db:
    image: mariadb:10.6
    container_name: npm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - npm_db_data:/var/lib/mysql
    networks:          
      - proxy-network
      
  # Nginx Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    env_file: .env
    depends_on:
      - npm-db
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:          
      - proxy-network

volumes:
  npm_db_data:
  npm_data:
  npm_letsencrypt:

networks:
  proxy-network:  
    external: true