services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:         
      - proxy-network
    ports:
      - "127.0.0.1:9000:9000" 
      - "127.0.0.1:9443:9443"

volumes:
  portainer_data:

networks:
  proxy-network:
    external: true